# Generated by Django 3.1.1 on 2020-10-02 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorias', '0001_initial'),
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('en espera', 'En espera'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('borrador', 'Borrador')], default='borrador', max_length=15)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('puntaje', models.IntegerField(blank=True, choices=[(None, '----'), (1, 'Malo'), (2, 'Regular'), (3, 'Pasable'), (4, 'Bueno'), (5, 'Excelente')], default=None, null=True)),
                ('categorias', models.ManyToManyField(blank=True, to='categorias.Categoria')),
                ('contratado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_hechos', to=settings.AUTH_USER_MODEL)),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='ofertas.oferta')),
            ],
        ),
    ]
