# Generated by Django 3.1.1 on 2020-10-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_auto_20201001_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='puntaje',
            field=models.IntegerField(blank=True, choices=[(None, '----'), (1, 'Malo'), (2, 'Regular'), (3, 'Pasable'), (4, 'Bueno'), (5, 'Excelente')], default=None, null=True),
        ),
    ]
