# Generated by Django 3.1.1 on 2020-10-02 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapps.cuentas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provincias', to='cuentas.pais')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default='img/perfiles/empty-profile.png', null=True, upload_to=myapps.cuentas.models.get_image_path)),
                ('descripcion', models.TextField(blank=True, max_length=1000)),
                ('puntuacion', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=13, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_calle', models.IntegerField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(blank=True, null=True, related_name='perfiles', to='categorias.Categoria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidades', to='cuentas.provincia')),
            ],
            options={
                'verbose_name_plural': 'Localidades',
            },
        ),
    ]
