# Generated by Django 3.1.1 on 2020-10-02 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domicilios_pais', to='cuentas.pais'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domicilios_provincia', to='cuentas.pais'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domicilios_localidad', to='cuentas.localidad'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='cuentas.domicilio'),
        ),
    ]
