# Generated by Django 3.1.1 on 2020-10-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_auto_20201006_2251'),
        ('cuentas', '0002_perfil_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='perfiles', to='categorias.Categoria'),
        ),
    ]
