# Generated by Django 3.1.1 on 2020-10-02 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_auto_20201002_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='domicilio',
        ),
        migrations.AddField(
            model_name='perfil',
            name='calle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_localidad', to='cuentas.localidad'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero_calle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_pais', to='cuentas.pais'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_provincia', to='cuentas.pais'),
        ),
        migrations.DeleteModel(
            name='Domicilio',
        ),
    ]
