# Generated by Django 3.1.1 on 2020-10-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20201002_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='provincia',
        ),
    ]
