# Generated by Django 3.1.1 on 2020-10-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('cuentas', '0004_auto_20201002_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='categorias',
            field=models.ManyToManyField(blank=True, null=True, related_name='perfiles', to='categorias.Categoria'),
        ),
    ]
