# Generated by Django 3.1.1 on 2020-10-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(blank=True, default='img/categorias/img_defecto/categoria-img.jpg', null=True, upload_to='img/categorias/'),
        ),
    ]
